@startuml CarGuy

entity User {
 * UID
 Username
 Password
 Publicname
 Description
 Title
 Image
 created_at
}

entity Post {
 * PID
 Title
 Type
 Content
 UID (FK)
 published_at
 Forum_id (FK)
 Likes
 Dislikes
}

entity Comment {
 * CID
 Content
 UID (FK)
 PID (FK)
 Parent_CID (FK)
 published_at
 Likes
 Dislikes
}

entity Forum {
 * Forum_id
 UID (FK)
 Name
 Description
 Parent_Forum_id (FK)
 Created_at
}

User "1" -- "0..*" Post : creates
User "1" -- "0..*" Comment : creates
User "1" -- "0..*" Forum : creates
Post "1" -- "0..*" Comment : has
Forum "1" -- "0..*" Post : contains
Forum "1" -- "0..*" Forum : contains
Comment "0..1" -- "0..*" Comment : replies to
@enduml